# Use the README file as a reference to customize settings.

Lab:
  fields:
    default: email, encrypted_password, title_lab, description, reset_password_token, reset_password_sent_at, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip, logo_file_name, logo_file_size
    form: email,  title_lab, logo, description, director_name, director_email
  relationships: students, fields
  application: Application
